const categories = [
    {
        id: 1,
        title: 'Gradients',
        images: [
            require('../assets/images/gradient/gradient1.png'),
            require('../assets/images/gradient/gradient2.png'),
            require('../assets/images/gradient/gradient3.png'),
            require('../assets/images/gradient/gradient4.png'),
            require('../assets/images/gradient/gradient5.png'),
            require('../assets/images/gradient/gradient6.jpg'),
            require('../assets/images/gradient/gradient7.png'),
            require('../assets/images/gradient/gradient8.png'),
            require('../assets/images/gradient/gradient9.png'),
        ],
    },
    {
        id: 2,
        title: 'Checkered',
        images: [
            require('../assets/images/checkered/checkered1.jpg'),
            require('../assets/images/checkered/checkered2.jpg'),
            require('../assets/images/checkered/checkered3.jpg'),
            require('../assets/images/checkered/checkered4.jpg'),
            require('../assets/images/checkered/checkered5.png'),
            require('../assets/images/checkered/checkered6.jpg'),
            require('../assets/images/checkered/checkered7.png'),
            require('../assets/images/checkered/checkered8.png'),
        ],
    },
    {
        id: 3,
        title: 'Animal',
        images: [
            require('../assets/images/animal/animal1.jpg'),
            require('../assets/images/animal/animal2.jpg'),
            require('../assets/images/animal/animal3.jpg'),
            require('../assets/images/animal/animal4.jpg'),
            require('../assets/images/animal/animal5.jpg'),
            require('../assets/images/animal/animal6.png'),
            require('../assets/images/animal/animal7.jpg'),
            require('../assets/images/animal/animal8.jpg'),
            require('../assets/images/animal/animal9.jpg'),
            require('../assets/images/animal/animal10.jpg'),
        ],
    },
    {
        id: 4,
        title: 'Hypnosis',
        images: [
            require('../assets/images/hypnosis/hypnosis1.jpg'),
            require('../assets/images/hypnosis/hypnosis2.jpg'),
            require('../assets/images/hypnosis/hypnosis3.jpg'),
            require('../assets/images/hypnosis/hypnosis4.jpg'),
            require('../assets/images/hypnosis/hypnosis5.jpg'),
            require('../assets/images/hypnosis/hypnosis6.jpg'),
            require('../assets/images/hypnosis/hypnosis7.jpg'),
            require('../assets/images/hypnosis/hypnosis8.jpg'),
            require('../assets/images/hypnosis/hypnosis9.jpg'),
        ],
    },
    {
        id: 5,
        title: 'Retro',
        images: [
            require('../assets/images/retro/retro1.jpg'),
            require('../assets/images/retro/retro2.jpg'),
            require('../assets/images/retro/retro3.jpg'),
            require('../assets/images/retro/retro4.jpg'),
            require('../assets/images/retro/retro5.jpg'),
            require('../assets/images/retro/retro6.jpg'),
            require('../assets/images/retro/retro7.jpg'),
            require('../assets/images/retro/retro8.jpg'),
        ],
    },
    {
        id: 6,
        title: 'Shine',
        images: [
            require('../assets/images/shine/shine1.jpg'),
            require('../assets/images/shine/shine2.jpg'),
            require('../assets/images/shine/shine3.jpg'),
            require('../assets/images/shine/shine4.jpg'),
            require('../assets/images/shine/shine5.jpg'),
            require('../assets/images/shine/shine6.jpg'),
            require('../assets/images/shine/shine7.jpg'),
            require('../assets/images/shine/shine8.jpg'),
            require('../assets/images/shine/shine9.jpg'),
        ],
    },
    {
        id: 7,
        title: 'Watercolor',
        images: [
            require('../assets/images/watercolor/watercolor1.jpg'),
            require('../assets/images/watercolor/watercolor2.jpg'),
            require('../assets/images/watercolor/watercolor3.jpg'),
            require('../assets/images/watercolor/watercolor4.jpg'),
            require('../assets/images/watercolor/watercolor5.jpg'),
            require('../assets/images/watercolor/watercolor6.jpg'),
            require('../assets/images/watercolor/watercolor7.jpg'),
            require('../assets/images/watercolor/watercolor8.jpg'),
        ],
    },
    {
        id: 8,
        title: 'White',
        images: [
            require('../assets/images/white/white1.jpg'),
            require('../assets/images/white/white3.jpeg'),
            require('../assets/images/white/white4.jpeg'),
            require('../assets/images/white/white5.jpeg'),
            require('../assets/images/white/white6.jpeg'),
            require('../assets/images/white/white7.jpeg'),
            require('../assets/images/white/white8.jpeg'),
            require('../assets/images/white/white9.jpg'),
        ],
    },
    {
        id: 9,
        title: 'Pixel',
        images: [
            require('../assets/images/pixel/pixel1.jpg'),
            require('../assets/images/pixel/pixel2.jpg'),
            require('../assets/images/pixel/pixel3.jpg'),
            require('../assets/images/pixel/pixel4.jpg'),
            require('../assets/images/pixel/pixel5.jpg'),
            require('../assets/images/pixel/pixel6.jpg'),
            require('../assets/images/pixel/pixel7.png'),
            require('../assets/images/pixel/pixel8.png'),
        ],
    },
    {
        id: 11,
        title: 'Dots',
        images: [
            require('../assets/images/dots/dots1.jpg'),
            require('../assets/images/dots/dots2.jpg'),
            require('../assets/images/dots/dots3.jpg'),
            require('../assets/images/dots/dots4.jpg'),
            require('../assets/images/dots/dots5.jpg'),
            require('../assets/images/dots/dots6.jpg'),
            require('../assets/images/dots/dots7.jpg'),
            require('../assets/images/dots/dots8.jpg'),
            require('../assets/images/dots/dots9.jpg'),
        ],
    },
    {
        id: 12,
        title: 'Floral',
        images: [
            require('../assets/images/floral/floral1.jpg'),
            require('../assets/images/floral/floral2.jpg'),
            require('../assets/images/floral/floral3.jpg'),
            require('../assets/images/floral/floral4.jpg'),
            require('../assets/images/floral/floral5.jpg'),
            require('../assets/images/floral/floral6.jpg'),
            require('../assets/images/floral/floral7.jpg'),
            require('../assets/images/floral/floral8.jpg'),
        ],
    },
    {
        id: 13,
        title: 'Glass',
        images: [
            require('../assets/images/glass/glass1.jpg'),
            require('../assets/images/glass/glass2.jpg'),
            require('../assets/images/glass/glass3.jpg'),
            require('../assets/images/glass/glass4.jpg'),
            require('../assets/images/glass/glass5.jpg'),
            require('../assets/images/glass/glass6.jpg'),
          
        ],
    },
    {
        id: 14,
        title: 'Neon',
        images: [
            require('../assets/images/neon/neon1.jpg'),
            require('../assets/images/neon/neon2.jpg'),
            require('../assets/images/neon/neon3.jpg'),
            require('../assets/images/neon/neon4.jpg'),
            require('../assets/images/neon/neon5.jpg'),
            require('../assets/images/neon/neon6.jpg'),
        ],
    },
    {
        id: 15,
        title: 'Rainbow',
        images: [
            require('../assets/images/rainbow/rainbow1.jpg'),
            require('../assets/images/rainbow/rainbow2.jpg'),
            require('../assets/images/rainbow/rainbow3.jpg'),
            require('../assets/images/rainbow/rainbow4.jpg'),
            require('../assets/images/rainbow/rainbow5.jpg'),
            require('../assets/images/rainbow/rainbow6.jpg'),
            require('../assets/images/rainbow/rainbow7.jpg'),
        ],
    },
    {
        id: 16,
        title: 'Silver',
        images: [
            require('../assets/images/silver/silver1.jpg'),
            require('../assets/images/silver/silver2.jpg'),
            require('../assets/images/silver/silver3.jpg'),
            require('../assets/images/silver/silver4.jpg'),
            require('../assets/images/silver/silver5.jpg'),
            require('../assets/images/silver/silver6.jpg'),
            require('../assets/images/silver/silver7.jpg'),
        ],
    },
    {
        id: 17,
        title: 'Summer',
        images: [
            require('../assets/images/summer/summer1.jpg'),
            require('../assets/images/summer/summer2.jpg'),
            require('../assets/images/summer/summer3.jpg'),
            require('../assets/images/summer/summer4.jpg'),
            require('../assets/images/summer/summer5.jpg'),
            require('../assets/images/summer/summer7.jpg'),
            require('../assets/images/summer/summer8.jpg'),
        ],
    },
    {
        id: 18,
        title: 'Geometric',
        images: [
            require('../assets/images/geometric/geometric1.jpg'),
            require('../assets/images/geometric/geometric2.jpg'),
            require('../assets/images/geometric/geometric3.jpg'),
            require('../assets/images/geometric/geometric4.jpg'),
            require('../assets/images/geometric/geometric5.jpg'),
            require('../assets/images/geometric/geometric7.jpg'),
            require('../assets/images/geometric/geometric8.jpg'),
        ],
    },
    // Add more categories as needed
];

export const data = {
    categories
}


// "Gradient", 
// "Checkereed", 
// "Animal", 
// "Hypnosis", 
// "Retro", 
// "Shine", 
// "Watercolor", 
// "White", 
// "Pixel", 
// "Dots", 
// "BW", 
// "Floral", 
// "Glass", 
// "Ornament", 
// "Neon", 
// "Rainmbow", 
// "Silver", 
// "Summer", 
// "Geometric", 